name: Build & Publish Docker Image

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for git inside container

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tags and push flag
        id: docker-meta
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          OWNER=${OWNER,,}

          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            IMAGE_TAG=${GITHUB_REF#refs/tags/}
            DO_PUSH=true
          else
            IMAGE_TAG=dev-${SHORT_SHA}
            DO_PUSH=false
          fi

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "DO_PUSH=$DO_PUSH" >> $GITHUB_ENV
          echo "OWNER=$OWNER" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./container/Dockerfile
          push: ${{ env.DO_PUSH }}
          tags: |
            ghcr.io/${{ env.OWNER }}/boom:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.OWNER }}/boom:latest
          platforms: linux/amd64,linux/arm64

